# Generated by Django 5.1.7 on 2025-05-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evacuationnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('file', models.FileField(blank=True, null=True, upload_to='instruction_materials/', verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.instruction')),
            ],
            options={
                'verbose_name': 'Материал инструктажа',
                'verbose_name_plural': 'Материалы инструктажей',
                'ordering': ['instruction', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InstructionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('passing_score', models.PositiveIntegerField(default=70, verbose_name='Проходной балл (%)')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='0 - без ограничения', verbose_name='Ограничение времени (мин)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('instruction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.instruction')),
            ],
            options={
                'verbose_name': 'Тест к инструктажу',
                'verbose_name_plural': 'Тесты к инструктажам',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.instructiontest')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.testquestion')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набранные баллы')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Максимальный балл')),
                ('score_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент правильных ответов')),
                ('passed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Проверен')),
                ('reviewer_notes', models.TextField(blank=True, null=True, verbose_name='Примечания проверяющего')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='core.employee')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.instructiontest')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.testanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.testquestion')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to='core.testresult')),
            ],
            options={
                'verbose_name': 'Ответ на тест',
                'verbose_name_plural': 'Ответы на тесты',
            },
        ),
    ]
